services:
  lint:
    image: buildkite/plugin-linter
    command: ['--id', 'peaudecastor/boost-security-scanner']
    volumes:
      - ".:/plugin:ro"
  tests:
    image: buildkite/plugin-tester
    volumes:
      - ".:/plugin:ro"
