name: Boost Security Scanner
description: Scans a repository for vulnerabilities
author: https://boostsecurity.io
requirements:
  - bash
  - docker
  - mktemp
configuration:
  properties:
    additional_args:
      description: List of additional CLI arguments to pass
      type: array
      items:
        type: string
    api_endpoint:
      description: Boost Security API endpoint override
      type: string
    api_token:
      description: Boost Security API token
      type: string
    scanner_version:
      description: Boost Security scanner version override
      type: string
    org_name:
      description: Repository organization name override
      type: string
    repo_name:
      description: Repository slug name override
      type: string
  additionalProperties: false
  required:
    - api_token
