#!/bin/bash

declare SELF="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
source ${SELF}/../lib/action.bash

main ()
{
  declare action=$(config.get "ACTION")

  if [ -z "${action:-}" ]; then
    log.error "the 'action' option must be one of 'scan', 'exec' or 'complete'"
    log.error "assuming default 'action' of 'scan'"
  fi

  case "${action:-scan}" in
    exec)       main.exec     ;;
    scan)       main.scan     ;;
    complete)   main.complete ;;
  esac
}

main
